INSERT INTO tms_carrier(code,name,type,api_provider,api_key,status) SELECT 'SELF01','自建车队','SELF',NULL,NULL,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_carrier WHERE code='SELF01');
INSERT INTO tms_carrier(code,name,type,api_provider,api_key,status) SELECT 'SF','顺丰模拟','THIRD_PARTY','MOCK_SF','demo','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_carrier WHERE code='SF');
INSERT INTO tms_carrier(code,name,type,api_provider,api_key,status) SELECT 'JD','京东模拟','THIRD_PARTY','MOCK_JD','demo','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_carrier WHERE code='JD');
INSERT INTO tms_vehicle(plate_no,vehicle_type,carrier_code,max_weight_kg,max_volume_m3,inner_length_cm,inner_width_cm,inner_height_cm,driver_code,status,lng,lat) SELECT '沪A12345','TRUCK_4M2','SELF01',2000,18,420,200,200,'DRV01','IDLE',121.47,31.23 WHERE NOT EXISTS(SELECT 1 FROM tms_vehicle WHERE plate_no='沪A12345');
INSERT INTO tms_vehicle(plate_no,vehicle_type,carrier_code,max_weight_kg,max_volume_m3,inner_length_cm,inner_width_cm,inner_height_cm,driver_code,status,lng,lat) SELECT '沪A12346','TRUCK_6M8','SELF01',8000,35,680,240,240,'DRV02','IDLE',121.47,31.23 WHERE NOT EXISTS(SELECT 1 FROM tms_vehicle WHERE plate_no='沪A12346');
INSERT INTO tms_vehicle(plate_no,vehicle_type,carrier_code,max_weight_kg,max_volume_m3,inner_length_cm,inner_width_cm,inner_height_cm,driver_code,status,lng,lat) SELECT '沪A12347','TRUCK_9M6','SELF01',12000,50,960,250,250,'DRV03','IDLE',121.47,31.23 WHERE NOT EXISTS(SELECT 1 FROM tms_vehicle WHERE plate_no='沪A12347');
INSERT INTO tms_driver(code,name,phone,license_type,carrier_code,status) SELECT 'DRV01','张师傅','13800000001','C1','SELF01','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_driver WHERE code='DRV01');
INSERT INTO tms_driver(code,name,phone,license_type,carrier_code,status) SELECT 'DRV02','李师傅','13800000002','B2','SELF01','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_driver WHERE code='DRV02');
INSERT INTO tms_driver(code,name,phone,license_type,carrier_code,status) SELECT 'DRV03','王师傅','13800000003','A2','SELF01','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_driver WHERE code='DRV03');
INSERT INTO tms_site(code,name,type,province,city,address,lng,lat) SELECT 'WH01','上海仓','WAREHOUSE','上海','上海','上海仓',121.47,31.23 WHERE NOT EXISTS(SELECT 1 FROM tms_site WHERE code='WH01');
INSERT INTO tms_site(code,name,type,province,city,address,lng,lat) SELECT 'HUB01','苏州分拨','HUB','江苏','苏州','苏州分拨',120.62,31.30 WHERE NOT EXISTS(SELECT 1 FROM tms_site WHERE code='HUB01');
INSERT INTO tms_site(code,name,type,province,city,address,lng,lat) SELECT 'ST01','杭州站','STATION','浙江','杭州','杭州站',120.15,30.27 WHERE NOT EXISTS(SELECT 1 FROM tms_site WHERE code='ST01');
INSERT INTO tms_customer(code,name,contact,phone,province,city,address,lng,lat) SELECT 'CUS01','苏州客户','客户一','13900000001','江苏','苏州','苏州客户地址',120.60,31.32 WHERE NOT EXISTS(SELECT 1 FROM tms_customer WHERE code='CUS01');
INSERT INTO tms_customer(code,name,contact,phone,province,city,address,lng,lat) SELECT 'CUS02','杭州客户','客户二','13900000002','浙江','杭州','杭州客户地址',120.15,30.27 WHERE NOT EXISTS(SELECT 1 FROM tms_customer WHERE code='CUS02');
INSERT INTO tms_customer(code,name,contact,phone,province,city,address,lng,lat) SELECT 'CUS03','上海客户','客户三','13900000003','上海','上海','上海客户地址',121.47,31.23 WHERE NOT EXISTS(SELECT 1 FROM tms_customer WHERE code='CUS03');
INSERT INTO tms_route(code,name,from_site_code,to_site_code,distance_km,estimated_hours,via_sites) SELECT 'R001','上海到杭州','WH01','ST01',200,4,'HUB01' WHERE NOT EXISTS(SELECT 1 FROM tms_route WHERE code='R001');
INSERT INTO tms_geofence(code,name,type,site_code,center_lng,center_lat,radius_m,alert_on_enter,alert_on_exit,status) SELECT 'GF_WH01','上海仓围栏','CIRCLE','WH01',121.47,31.23,3000,TRUE,TRUE,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_geofence WHERE code='GF_WH01');
INSERT INTO tms_geofence(code,name,type,site_code,center_lng,center_lat,radius_m,alert_on_enter,alert_on_exit,status) SELECT 'GF_HUB01','苏州围栏','CIRCLE','HUB01',120.62,31.30,5000,TRUE,TRUE,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_geofence WHERE code='GF_HUB01');
INSERT INTO tms_geofence(code,name,type,site_code,polygon,alert_on_enter,alert_on_exit,status) SELECT 'GF_ST01','杭州围栏','POLYGON','ST01','[[120.10,30.22],[120.20,30.22],[120.20,30.32],[120.10,30.32]]',TRUE,TRUE,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_geofence WHERE code='GF_ST01');
INSERT INTO tms_rate_rule(code,name,carrier_code,charge_type,first_unit,first_price,add_unit,add_price,min_charge,volume_ratio,priority,status) SELECT 'RR_WEIGHT','通用重量','WEIGHT','WEIGHT',3,10,1,1.5,10,6000,20,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_rate_rule WHERE code='RR_WEIGHT');
INSERT INTO tms_rate_rule(code,name,carrier_code,charge_type,first_unit,first_price,add_unit,add_price,min_charge,volume_ratio,priority,status) SELECT 'RR_SF','顺丰重量','SF','WEIGHT',1,12,1,3,12,6000,1,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_rate_rule WHERE code='RR_SF');
INSERT INTO tms_rate_rule(code,name,carrier_code,charge_type,first_unit,first_price,add_unit,add_price,min_charge,volume_ratio,priority,status) SELECT 'RR_SELF_DISTANCE','自建里程','SELF01','DISTANCE',50,300,10,40,300,6000,1,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_rate_rule WHERE code='RR_SELF_DISTANCE');
INSERT INTO tms_rate_rule(code,name,carrier_code,charge_type,first_unit,first_price,add_unit,add_price,min_charge,volume_ratio,priority,status) SELECT 'RR_VOLUME','通用体积',NULL,'VOLUME',1,150,.1,15,150,6000,30,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_rate_rule WHERE code='RR_VOLUME');
INSERT INTO tms_rate_rule(code,name,carrier_code,charge_type,first_unit,first_price,add_unit,add_price,min_charge,volume_ratio,priority,status) SELECT 'RR_PIECE','通用件数',NULL,'PIECE',1,8,1,5,8,6000,40,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_rate_rule WHERE code='RR_PIECE');
INSERT INTO tms_transport_order(code,source_no,customer_code,order_type,from_site_code,consignee_name,consignee_address,consignee_lng,consignee_lat,total_qty,total_weight_kg,total_volume_m3,volumetric_weight_kg,chargeable_weight_kg,volume_ratio,status,priority) SELECT 'TO-DEMO01','DEMO01','CUS01','DELIVERY','WH01','苏州客户','苏州客户地址',120.60,31.32,2,6,.2,33.333,33.333,6000,'CREATED',5 WHERE NOT EXISTS(SELECT 1 FROM tms_transport_order WHERE code='TO-DEMO01');
INSERT INTO tms_transport_order_line(order_id,item_code,item_name,qty,length_cm,width_cm,height_cm,weight_kg,line_weight_kg,line_volume_m3) SELECT id,'DEMO-SKU','演示货物',2,100,50,20,3,6,.2 FROM tms_transport_order WHERE code='TO-DEMO01' AND NOT EXISTS(SELECT 1 FROM tms_transport_order_line WHERE order_id=tms_transport_order.id);
INSERT INTO tms_transport_order(code,source_no,customer_code,order_type,from_site_code,consignee_name,consignee_address,consignee_lng,consignee_lat,total_qty,total_weight_kg,total_volume_m3,volumetric_weight_kg,chargeable_weight_kg,volume_ratio,status,priority) SELECT 'TO-DEMO02','DEMO02','CUS02','DELIVERY','WH01','杭州客户','杭州客户地址',120.15,30.27,1,2,.1,16.667,16.667,6000,'CREATED',5 WHERE NOT EXISTS(SELECT 1 FROM tms_transport_order WHERE code='TO-DEMO02');
INSERT INTO tms_transport_order_line(order_id,item_code,item_name,qty,length_cm,width_cm,height_cm,weight_kg,line_weight_kg,line_volume_m3) SELECT id,'DEMO-SKU2','演示货物',1,100,50,20,2,2,.1 FROM tms_transport_order WHERE code='TO-DEMO02' AND NOT EXISTS(SELECT 1 FROM tms_transport_order_line WHERE order_id=tms_transport_order.id);
INSERT INTO tms_waybill(code,carrier_code,carrier_type,from_site_code,planned_depart_time,planned_arrive_time,order_count,total_weight_kg,total_volume_m3,freight_amount,status,exception_flag,created_at,updated_at)
SELECT 'WB-IR-DELAY','SF','THIRD_PARTY','WH01',TIMESTAMPADD(HOUR,-6,CURRENT_TIMESTAMP),TIMESTAMPADD(HOUR,-2,CURRENT_TIMESTAMP),1,6,.2,18,'IN_TRANSIT',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
WHERE NOT EXISTS(SELECT 1 FROM tms_waybill WHERE code='WB-IR-DELAY');
INSERT INTO tms_transport_order(code,source_no,customer_code,order_type,from_site_code,consignee_name,consignee_address,consignee_lng,consignee_lat,total_qty,total_weight_kg,total_volume_m3,volumetric_weight_kg,chargeable_weight_kg,volume_ratio,status,priority,waybill_id,waybill_code)
SELECT 'TO-IR-DELAY','IR-SO-STUCK','CUS03','DELIVERY','WH01','IR延误客户','上海客户地址',121.47,31.23,1,6,.2,33.333,33.333,6000,'IN_TRANSIT',10,
(SELECT id FROM tms_waybill WHERE code='WB-IR-DELAY'),'WB-IR-DELAY'
WHERE NOT EXISTS(SELECT 1 FROM tms_transport_order WHERE code='TO-IR-DELAY');
INSERT INTO tms_waybill(code,carrier_code,carrier_type,from_site_code,planned_depart_time,planned_arrive_time,order_count,total_weight_kg,total_volume_m3,freight_amount,status,exception_flag,created_at,updated_at)
SELECT 'WB-IR-CREATED','SF','THIRD_PARTY','WH01',TIMESTAMPADD(HOUR,1,CURRENT_TIMESTAMP),TIMESTAMPADD(HOUR,8,CURRENT_TIMESTAMP),1,4,.1,0,'CREATED',FALSE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
WHERE NOT EXISTS(SELECT 1 FROM tms_waybill WHERE code='WB-IR-CREATED');
INSERT INTO tms_transport_order(code,source_no,customer_code,order_type,from_site_code,consignee_name,consignee_address,consignee_lng,consignee_lat,total_qty,total_weight_kg,total_volume_m3,volumetric_weight_kg,chargeable_weight_kg,volume_ratio,status,priority,waybill_id,waybill_code)
SELECT 'TO-IR-CREATED','IR-SO-CREATED','CUS03','DELIVERY','WH01','IR待调度客户','上海客户地址',121.47,31.23,1,4,.1,16.667,16.667,6000,'DISPATCHED',8,
(SELECT id FROM tms_waybill WHERE code='WB-IR-CREATED'),'WB-IR-CREATED'
WHERE NOT EXISTS(SELECT 1 FROM tms_transport_order WHERE code='TO-IR-CREATED');
INSERT INTO tms_waybill(code,carrier_code,carrier_type,from_site_code,planned_depart_time,planned_arrive_time,order_count,total_weight_kg,total_volume_m3,freight_amount,status,exception_flag,created_at,updated_at)
SELECT 'WB-IR-EXC','SF','THIRD_PARTY','WH01',TIMESTAMPADD(HOUR,-8,CURRENT_TIMESTAMP),TIMESTAMPADD(HOUR,-1,CURRENT_TIMESTAMP),1,3,.1,22,'IN_TRANSIT',TRUE,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP
WHERE NOT EXISTS(SELECT 1 FROM tms_waybill WHERE code='WB-IR-EXC');
INSERT INTO tms_transport_order(code,source_no,customer_code,order_type,from_site_code,consignee_name,consignee_address,consignee_lng,consignee_lat,total_qty,total_weight_kg,total_volume_m3,volumetric_weight_kg,chargeable_weight_kg,volume_ratio,status,priority,waybill_id,waybill_code)
SELECT 'TO-IR-EXC','IR-SO-EXC','CUS03','DELIVERY','WH01','IR异常客户','上海客户地址',121.47,31.23,1,3,.1,16.667,16.667,6000,'IN_TRANSIT',9,
(SELECT id FROM tms_waybill WHERE code='WB-IR-EXC'),'WB-IR-EXC'
WHERE NOT EXISTS(SELECT 1 FROM tms_transport_order WHERE code='TO-IR-EXC');
INSERT INTO tms_freight_bill(code,waybill_id,waybill_code,order_id,order_code,carrier_code,rule_code,charge_type,quantity,amount,status,created_at,updated_at)
SELECT 'FB-IR-DELAY', w.id, 'WB-IR-DELAY', o.id, 'TO-IR-DELAY', 'SF', 'RR_SF', 'WEIGHT', 6, 18, 'UNPAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM tms_waybill w
JOIN tms_transport_order o ON o.code='TO-IR-DELAY'
WHERE w.code='WB-IR-DELAY'
AND NOT EXISTS(SELECT 1 FROM tms_freight_bill WHERE code='FB-IR-DELAY');
INSERT INTO tms_freight_bill(code,waybill_id,waybill_code,order_id,order_code,carrier_code,rule_code,charge_type,quantity,amount,status,created_at,updated_at)
SELECT 'FB-IR-EXC', w.id, 'WB-IR-EXC', o.id, 'TO-IR-EXC', 'SF', 'RR_SF', 'WEIGHT', 3, 22, 'UNPAID', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM tms_waybill w
JOIN tms_transport_order o ON o.code='TO-IR-EXC'
WHERE w.code='WB-IR-EXC'
AND NOT EXISTS(SELECT 1 FROM tms_freight_bill WHERE code='FB-IR-EXC');
INSERT INTO tms_region(code,name,level,provinces,cities,status) SELECT 'EAST','华东','REGION','上海,江苏,浙江,安徽','上海,苏州,杭州,南京','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_region WHERE code='EAST');
INSERT INTO tms_region(code,name,level,provinces,cities,status) SELECT 'NORTH','华北','REGION','北京,天津,河北,山东','北京,天津,济南','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_region WHERE code='NORTH');
INSERT INTO tms_region(code,name,level,provinces,cities,status) SELECT 'SOUTH','华南','REGION','广东,广西,福建','广州,深圳,厦门','ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_region WHERE code='SOUTH');
INSERT INTO tms_service_level(code,name,promised_hours,priority,status) SELECT 'STANDARD','标准达','48',3,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_service_level WHERE code='STANDARD');
INSERT INTO tms_service_level(code,name,promised_hours,priority,status) SELECT 'EXPRESS','次日达','24',1,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_service_level WHERE code='EXPRESS');
INSERT INTO tms_service_level(code,name,promised_hours,priority,status) SELECT 'ECONOMY','经济达','72',5,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_service_level WHERE code='ECONOMY');
INSERT INTO tms_package_material(code,name,length_cm,width_cm,height_cm,tare_weight_kg,volume_m3,status) SELECT 'BOX_SMALL','小纸箱',30,20,20,.2,.012,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_package_material WHERE code='BOX_SMALL');
INSERT INTO tms_package_material(code,name,length_cm,width_cm,height_cm,tare_weight_kg,volume_m3,status) SELECT 'BOX_MEDIUM','中纸箱',60,40,40,.5,.096,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_package_material WHERE code='BOX_MEDIUM');
INSERT INTO tms_package_material(code,name,length_cm,width_cm,height_cm,tare_weight_kg,volume_m3,status) SELECT 'BOX_LARGE','大纸箱',100,60,60,1, .36,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_package_material WHERE code='BOX_LARGE');
INSERT INTO tms_carrier_coverage(carrier_code,region_code,service_level_code,promised_hours,status) SELECT 'SELF01','EAST','STANDARD',48,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_carrier_coverage WHERE carrier_code='SELF01' AND region_code='EAST');
INSERT INTO tms_carrier_coverage(carrier_code,region_code,service_level_code,promised_hours,status) SELECT 'SF','EAST','EXPRESS',24,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_carrier_coverage WHERE carrier_code='SF' AND region_code='EAST');
INSERT INTO tms_carrier_coverage(carrier_code,region_code,service_level_code,promised_hours,status) SELECT 'JD','NORTH','STANDARD',36,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_carrier_coverage WHERE carrier_code='JD' AND region_code='NORTH');
INSERT INTO tms_selection_rule(code,name,strategy,region_code,priority,status) SELECT 'SEL_EAST','华东成本优先','COST','EAST',1,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_selection_rule WHERE code='SEL_EAST');
INSERT INTO tms_selection_rule(code,name,strategy,region_code,priority,status) SELECT 'SEL_NORTH','华北时效优先','TIME','NORTH',1,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_selection_rule WHERE code='SEL_NORTH');
UPDATE tms_customer SET api_key='demo-key-001',callback_url='http://localhost:8080/api/push-log/mock-receiver',push_enabled=TRUE WHERE code='CUS01';
INSERT INTO tms_rate_rule(code,name,carrier_code,region_code,service_level_code,charge_type,first_unit,first_price,add_unit,add_price,min_charge,volume_ratio,priority,status) SELECT 'RR_SF_EAST_EXP','顺丰华东次日','SF','EAST','EXPRESS','WEIGHT',1,10,1,2,10,6000,1,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_rate_rule WHERE code='RR_SF_EAST_EXP');
INSERT INTO tms_rate_rule(code,name,carrier_code,region_code,service_level_code,charge_type,first_unit,first_price,add_unit,add_price,min_charge,volume_ratio,priority,status) SELECT 'RR_SELF_EAST','自建华东','SELF01','EAST',NULL,'WEIGHT',1,8,1,1.5,8,6000,2,'ENABLED' WHERE NOT EXISTS(SELECT 1 FROM tms_rate_rule WHERE code='RR_SELF_EAST');
INSERT INTO tms_waybill(code,carrier_code,carrier_type,vehicle_plate,driver_code,driver_name,from_site_code,status,order_count,total_weight_kg,total_volume_m3,exception_flag,planned_depart_time,actual_depart_time,planned_arrive_time,promised_arrive_time,service_level_code,created_at,updated_at,remark) SELECT 'WB-DEMO-OVERDUE','SELF01','SELF','沪A12345','DRV01',(SELECT name FROM tms_driver WHERE code='DRV01'),'WH01','IN_TRANSIT',0,0,0,FALSE,DATEADD('HOUR',-30,CURRENT_TIMESTAMP),DATEADD('HOUR',-29,CURRENT_TIMESTAMP),DATEADD('HOUR',-5,CURRENT_TIMESTAMP),DATEADD('HOUR',-5,CURRENT_TIMESTAMP),'STANDARD',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'演示：超过承诺到达时间的在途运单' WHERE NOT EXISTS(SELECT 1 FROM tms_waybill WHERE code='WB-DEMO-OVERDUE');
